--PostgreSQL--

CREATE USER cpmdb WITH PASSWORD 'poiu1234';
GRANT ALL PRIVILEGES ON DATABASE tutorial to cpmdb;

CREATE TABLE T_UMBS_POST (
    ID			int PRIMARY KEY,
	TITLE		VARCHAR(200) ,
    CATEGORIES	VARCHAR(200) ,
    CONTENT	    VARCHAR(5000) 
)